// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEQTAml1JFY-0ZPbN3YShF3Ugbt-5H7l8',
    appId: '1:282423168078:web:067ee6033a6108007a071f',
    messagingSenderId: '282423168078',
    projectId: 'bookstoreapp-804d7',
    authDomain: 'bookstoreapp-804d7.firebaseapp.com',
    storageBucket: 'bookstoreapp-804d7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd1B-VuIDhqBesh-yyfdQe9WOov9grKTE',
    appId: '1:282423168078:android:3e9cf7444364e6de7a071f',
    messagingSenderId: '282423168078',
    projectId: 'bookstoreapp-804d7',
    storageBucket: 'bookstoreapp-804d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAnXXEsWIgNCY505ZuNpsupYQmyretkqg',
    appId: '1:282423168078:ios:09088bcca7c845877a071f',
    messagingSenderId: '282423168078',
    projectId: 'bookstoreapp-804d7',
    storageBucket: 'bookstoreapp-804d7.firebasestorage.app',
    iosBundleId: 'com.example.bookStore2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAnXXEsWIgNCY505ZuNpsupYQmyretkqg',
    appId: '1:282423168078:ios:09088bcca7c845877a071f',
    messagingSenderId: '282423168078',
    projectId: 'bookstoreapp-804d7',
    storageBucket: 'bookstoreapp-804d7.firebasestorage.app',
    iosBundleId: 'com.example.bookStore2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEQTAml1JFY-0ZPbN3YShF3Ugbt-5H7l8',
    appId: '1:282423168078:web:47486c26bcfbaee17a071f',
    messagingSenderId: '282423168078',
    projectId: 'bookstoreapp-804d7',
    authDomain: 'bookstoreapp-804d7.firebaseapp.com',
    storageBucket: 'bookstoreapp-804d7.firebasestorage.app',
  );
}
